version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:local
    env_file:
      - .local.env
    networks:
      - webnet
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - mysql:/var/lib/mysql
networks:
  webnet:
volumes:
  mysql: